### PR TITLE
Update Gemfile.lock

### PR DESCRIPTION
**Pull request by anantshri**
upgrading packages within the rails and ruby constraints

### CODE REVIEW

**Comment by anantshri** [comment]
@abhisek need your review and confirmation. Brakeman is failing coz of older rails version but test cases are passing.

**Comment by anantshri** [comment]
This should also be fixing #120

**Comment by anantshri** [comment]
Note the rails build is failing at brakeman as we are still in older version of rails.

**Comment by abhisek** [comment]
@anantshri Do we still need to update the dependencies in `Gemfile.lock`. I am a bit scared of doing it because I don't know what will break. We do not have a very good test coverage and our CI build is breaking currently due to old version of bundler

**Pull request closed without merging**
